image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3001
    onOpen: open-preview
    visibility: public
  - port: 3306
    onOpen: ignore
    visibility: public
tasks:
  - init: |
      cp .env.example .env &&
      pipenv install &&
      mysql -u root -e "CREATE DATABASE example" &&
      pipenv run init &&
      pipenv run migrate &&
      pipenv run upgrade;
      command: >
      pipenv run start;
  - command: >
      ((sed -i /BACKEND_URL/d .env && echo "" >> .env && echo "BACKEND_URL=https://3001-${GITPOD_WORKSPACE_URL:8}" >> .env) || true) && 
      npm install &&
      python docs/assets/greeting.py front
    openMode: split-right

vscode:
  extensions:
    - esbenp.prettier-vscode
